package vista;

import Exepciones.CruzanHorariosEstudianteExepcion;
import Exepciones.ElEstudianteNoesDeEsteProgramaExepcion;
import Exepciones.EstudianteNoSeEliminoDelCursoExepcion;
import Exepciones.EstudianteYaExisteEnElCursoExepcion;
import Exepciones.NoSeEncuentraElCursoParaEliminarExepcion;
import Exepciones.NoSeGuardoElCursoExepcion;
import Exepciones.SoloPuedeHaberUnCursoConEsaJornadaExepcion;
import Exepciones.YaExisteUnCursoGuardadoConEstasMismasCaracteristicasExepcion;
import Util.IList;
import Util.Lista;
import controladores.ControladorCurso;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import modelo.Accion;
import modelo.Curso;
import modelo.Docente;
import modelo.Estudiante;
import modelo.Horario;
import modelo.Materia;
import modelo.NumJornada;
import modelo.Programa;
import modelo.NumRol;
import modelo.Persona;

/**
 *
 * @author JOAN
 */
public class VentanaRegistroCurso extends javax.swing.JFrame {

    ControladorCurso controlador;
    IList<Curso> listaCurso;
    IList<Estudiante> listaestudiante;

    public VentanaRegistroCurso() {
        initComponents();
        setLocationRelativeTo(this);
        this.controlador = new ControladorCurso();
        llenarCurso();
        llenarPeriodo();
        llenarJornada();
        llenarDocente();
        llenarPrograma();
        llenarEstudiante();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCurso = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbxMateria = new javax.swing.JComboBox<>();
        txtLlenarPeriodo = new javax.swing.JTextField();
        cbxDocente = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cbxJornada = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        cbxPrograma = new javax.swing.JComboBox<>();
        txtCodigo = new javax.swing.JTextField();
        btnDehacer = new javax.swing.JButton();
        btnRehacer = new javax.swing.JButton();
        btnHorario = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        Curso = new javax.swing.JLabel();
        cbxCurso = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbxEstudiante = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCursoEstudiante = new javax.swing.JTable();
        btnRegistrarEst = new javax.swing.JButton();
        btnAtras2 = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cbxHorario = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GESTIÓN CURSO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        tblCurso.setBackground(new java.awt.Color(204, 204, 204));
        tblCurso.setForeground(new java.awt.Color(0, 0, 0));
        tblCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCurso);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Docente:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Materia:");

        txtLlenarPeriodo.setEditable(false);
        txtLlenarPeriodo.setBackground(new java.awt.Color(204, 204, 204));
        txtLlenarPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLlenarPeriodoActionPerformed(evt);
            }
        });

        cbxDocente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxDocenteItemStateChanged(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(204, 255, 204));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 153, 153));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Codigo:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Jornada:");

        btnAtras.setBackground(new java.awt.Color(204, 204, 204));
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Atras.png"))); // NOI18N
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Programa:");

        cbxPrograma.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxProgramaItemStateChanged(evt);
            }
        });

        btnDehacer.setBackground(new java.awt.Color(102, 102, 102));
        btnDehacer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDehacer.setForeground(new java.awt.Color(255, 255, 255));
        btnDehacer.setText("Deshacer Ultima Accion");
        btnDehacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDehacerActionPerformed(evt);
            }
        });

        btnRehacer.setBackground(new java.awt.Color(102, 102, 102));
        btnRehacer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRehacer.setForeground(new java.awt.Color(255, 255, 255));
        btnRehacer.setText("Rehacer Ultima Accion");
        btnRehacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRehacerActionPerformed(evt);
            }
        });

        btnHorario.setBackground(new java.awt.Color(204, 204, 204));
        btnHorario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHorario.setForeground(new java.awt.Color(0, 0, 0));
        btnHorario.setText("Horario");
        btnHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHorarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnDehacer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRehacer))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEliminar)
                                .addGap(19, 19, 19))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxDocente, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxMateria, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxJornada, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxPrograma, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(7, 7, 7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLlenarPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAtras))
                        .addGap(179, 179, 179)
                        .addComponent(btnHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtLlenarPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxJornada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRehacer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDehacer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnHorario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Curso", jPanel2);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTRAR ESTUDIANTE A CURSO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        Curso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Curso.setForeground(new java.awt.Color(0, 0, 0));
        Curso.setText("Curso:");

        cbxCurso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxCursoItemStateChanged(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Estudiante:");

        tblCursoEstudiante.setBackground(new java.awt.Color(204, 204, 204));
        tblCursoEstudiante.setForeground(new java.awt.Color(0, 0, 0));
        tblCursoEstudiante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblCursoEstudiante);

        btnRegistrarEst.setBackground(new java.awt.Color(204, 255, 204));
        btnRegistrarEst.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegistrarEst.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrarEst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Guardar.png"))); // NOI18N
        btnRegistrarEst.setText("Registrar");
        btnRegistrarEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarEstActionPerformed(evt);
            }
        });

        btnAtras2.setBackground(new java.awt.Color(204, 204, 204));
        btnAtras2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Atras.png"))); // NOI18N
        btnAtras2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtras2ActionPerformed(evt);
            }
        });

        btnEliminar1.setBackground(new java.awt.Color(255, 153, 153));
        btnEliminar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar1.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Eliminar.png"))); // NOI18N
        btnEliminar1.setText("Eliminar");
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Horario:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAtras2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(Curso)
                                .addGap(34, 34, 34))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(btnRegistrarEst, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Curso, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegistrarEst, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addComponent(btnAtras2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Estudiante", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            if (CamposVacios()) {
                String codigo = txtCodigo.getText();
                Programa programa = (Programa) cbxPrograma.getSelectedItem();
                Materia materia = (Materia) cbxMateria.getSelectedItem();
                Docente docente = (Docente) cbxDocente.getSelectedItem();
                String periodo = txtLlenarPeriodo.getText();
                NumJornada jornada = (NumJornada) cbxJornada.getSelectedItem();
                Curso curso = new Curso(codigo, programa, materia, docente, periodo, jornada);
                controlador.guardarCurso(curso);
                JOptionPane.showMessageDialog(null, "Se guardo el curso");
                actualizarTabla(docente);
                limpiarCurso();
                llenarCurso();
            } else {
                JOptionPane.showMessageDialog(null, "Favor no dejar Campos VACIOS");
            }
        } catch (NoSeGuardoElCursoExepcion | YaExisteUnCursoGuardadoConEstasMismasCaracteristicasExepcion | SoloPuedeHaberUnCursoConEsaJornadaExepcion exp) {
            JOptionPane.showMessageDialog(null, exp.getMessage());
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
            String codigo = txtCodigo.getText();
            Docente docente = (Docente) cbxDocente.getSelectedItem();
            controlador.eliminarCurso(codigo);
            JOptionPane.showMessageDialog(null, "Se elimino el curso");
            actualizarTabla(docente);
            limpiarCurso();
            llenarCurso();
        } catch (NoSeEncuentraElCursoParaEliminarExepcion exp) {
            JOptionPane.showMessageDialog(null, exp.getMessage());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        VentanaAdministrador ventana = new VentanaAdministrador();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnRegistrarEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarEstActionPerformed
        try {
            if (CamposVaciosEst()) {
                Curso curso = (Curso) cbxCurso.getSelectedItem();
                Estudiante estudiante = (Estudiante) cbxEstudiante.getSelectedItem();
                controlador.guardarCursoEstud(estudiante, curso);
                actualizarTablaEstudi(curso);
                limpiarCursoEst();
                JOptionPane.showMessageDialog(null, "Se registro el estudiante al curso");
            } else {
                JOptionPane.showMessageDialog(null, "Favor no dejar Campos VACIOS");
            }
        } catch (EstudianteYaExisteEnElCursoExepcion | CruzanHorariosEstudianteExepcion exp) {
            JOptionPane.showMessageDialog(null, exp.getMessage());
        }
    }//GEN-LAST:event_btnRegistrarEstActionPerformed

    private void btnAtras2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtras2ActionPerformed
        VentanaAdministrador ventana = new VentanaAdministrador();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtras2ActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        try {
            Curso curso = (Curso) cbxCurso.getSelectedItem();
            Estudiante estudiante = (Estudiante) cbxEstudiante.getSelectedItem();
            JOptionPane.showMessageDialog(null, "Se eliminio el estudiante al curso");
            controlador.eliminarCursoEstud(curso, estudiante);
            actualizarTablaEstudi(curso);
            limpiarCursoEst();
        } catch (EstudianteNoSeEliminoDelCursoExepcion exp) {
            JOptionPane.showMessageDialog(null, exp.getMessage());
        }
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void cbxDocenteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxDocenteItemStateChanged
        Docente docente = (Docente) cbxDocente.getSelectedItem();
        actualizarTabla(docente);
    }//GEN-LAST:event_cbxDocenteItemStateChanged

    private void cbxCursoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxCursoItemStateChanged
        Curso curso = (Curso) cbxCurso.getSelectedItem();
        actualizarTablaEstudi(curso);
        llenarHorario(curso);
    }//GEN-LAST:event_cbxCursoItemStateChanged

    private void cbxProgramaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxProgramaItemStateChanged
        Programa programa = (Programa) cbxPrograma.getSelectedItem();
        llenarMateria(programa);
    }//GEN-LAST:event_cbxProgramaItemStateChanged

    private void txtLlenarPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLlenarPeriodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLlenarPeriodoActionPerformed

    private void btnDehacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDehacerActionPerformed
        controlador.dehacer();
        Docente docente = (Docente) cbxDocente.getSelectedItem();
        actualizarTabla(docente);
    }//GEN-LAST:event_btnDehacerActionPerformed

    private void btnRehacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRehacerActionPerformed
        controlador.rehacer();
        Docente docente = (Docente) cbxDocente.getSelectedItem();
        actualizarTabla(docente);
    }//GEN-LAST:event_btnRehacerActionPerformed

    private void btnHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHorarioActionPerformed
        int fila = tblCurso.getSelectedRow();
        if (fila != -1) {
            String codigo = (String) tblCurso.getValueAt(fila, 0);
            Curso curso = controlador.buscarCurso(codigo);
            VentanaRegistroHorario ventana = new VentanaRegistroHorario(curso);
            ventana.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnHorarioActionPerformed

    private void actualizarTabla(Docente docente) {
        listaCurso = new Lista<>();
        for (int i = 0; i < controlador.getListaCurso().size(); i++) {
            if (docente.getCodigo().equals(controlador.getListaCurso().get(i).getDocente().getCodigo())) {
                listaCurso.add(controlador.getListaCurso().get(i));
            }
        }
        DefaultTableModel modelo = new DefaultTableModel(new String[]{"CODIGO", "DOCENTE", "JORNADA", "MATERIA",
            "PERIODO"},
                listaCurso.size());
        tblCurso.setModel(modelo);
        TableModel modeloDatos = tblCurso.getModel();
        for (int i = 0; i < listaCurso.size(); i++) {
            Curso aux = listaCurso.get(i);
            modeloDatos.setValueAt(aux.getCodigoCurso(), i, 0);
            modeloDatos.setValueAt(aux.getDocente(), i, 1);
            modeloDatos.setValueAt(aux.getJornada(), i, 2);
            modeloDatos.setValueAt(aux.getMateria(), i, 3);
            modeloDatos.setValueAt(aux.getPeriodo(), i, 4);
        }
    }

    private void actualizarTablaEstudi(Curso curso) {
        listaestudiante = new Lista<>();
        for (int i = 0; i < controlador.getListaCurso().size(); i++) {
            for (int j = 0; j < controlador.getListaCurso().get(i).getListaEstudiates().size(); j++) {
                if (curso.getCodigoCurso().equals(controlador.getListaCurso().get(i).getCodigoCurso())) {
                    listaestudiante.add(controlador.getListaCurso().get(i).getListaEstudiates().get(j));
                }
            }
        }
        DefaultTableModel modelo = new DefaultTableModel(new String[]{"NOMBRE", "CODIGO", "PROGRAMA"},
                listaestudiante.size());
        tblCursoEstudiante.setModel(modelo);
        TableModel modeloDatos = tblCursoEstudiante.getModel();
        for (int i = 0; i < listaestudiante.size(); i++) {
            Estudiante aux = listaestudiante.get(i);
            modeloDatos.setValueAt(aux.getNombre(), i, 0);
            modeloDatos.setValueAt(aux.getCodigo(), i, 1);
            modeloDatos.setValueAt(aux.getPrograma(), i, 2);
        }
    }

    private void llenarPrograma() {
        cbxPrograma.removeAllItems();
        IList<Programa> listaPrograma = controlador.getListaPrograma();
        for (int i = 0; i < listaPrograma.size(); i++) {
            cbxPrograma.addItem(listaPrograma.get(i));
        }
    }

    private void llenarPeriodo() {
        txtLlenarPeriodo.setText(String.valueOf(controlador.obtenerPeriodoActual()));
    }

    private void llenarMateria(Programa programa) {
        cbxMateria.removeAllItems();
        IList<Materia> listaMateria = programa.getListaMateria();
        for (int i = 0; i < listaMateria.size(); i++) {
            cbxMateria.addItem(listaMateria.get(i));
        }
    }

    private void llenarJornada() {
        cbxJornada.addItem(NumJornada.DIA);
        cbxJornada.addItem(NumJornada.NOCHE);
    }

    private void llenarDocente() {
        cbxDocente.removeAllItems();
        IList<Persona> listaDocente = controlador.getListaPersona();
        for (int i = 0; i < listaDocente.size(); i++) {
            if (listaDocente.get(i).getRol().equals(NumRol.DOCENTE)) {
                cbxDocente.addItem((Docente) listaDocente.get(i));
            }
        }
    }

    private void llenarHorario(Curso curso) {
        cbxHorario.removeAllItems();
        if (curso != null) {
            IList<Horario> listaHorario = curso.getListaHorario();
            for (int i = 0; i < listaHorario.size(); i++) {
                cbxHorario.addItem(listaHorario.get(i));
            }
        }
    }

    private void llenarCurso() {
        cbxCurso.removeAllItems();
        IList<Curso> listaCurso = controlador.getListaCurso();
        for (int i = 0; i < listaCurso.size(); i++) {
            cbxCurso.addItem(listaCurso.get(i));
        }
    }

    private void llenarEstudiante() {
        cbxEstudiante.removeAllItems();
        IList<Persona> listaEstudiante = controlador.getListaPersona();
        for (int i = 0; i < listaEstudiante.size(); i++) {
            if (listaEstudiante.get(i).getRol().equals(NumRol.ESTUDIANTE)) {
                cbxEstudiante.addItem((Estudiante) listaEstudiante.get(i));
            }
        }
    }

    private void limpiarCurso() {
        txtCodigo.setText("");
        cbxJornada.setSelectedIndex(-1);
    }

    private void limpiarCursoEst() {
        cbxEstudiante.setSelectedIndex(-1);
    }

    public boolean CamposVaciosEst() {
        if (cbxCurso.getSelectedIndex() == -1 || cbxEstudiante.getSelectedIndex() == -1 || cbxHorario.getSelectedIndex() == -1) {
            return false;
        } else {
            return true;
        }
    }

    public boolean CamposVacios() {
        if (txtCodigo.getText().isEmpty() || cbxJornada.getSelectedIndex() == -1) {
            return false;
        } else {
            return true;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Curso;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnAtras2;
    private javax.swing.JButton btnDehacer;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnHorario;
    private javax.swing.JButton btnRegistrarEst;
    private javax.swing.JButton btnRehacer;
    private javax.swing.JComboBox<Curso> cbxCurso;
    private javax.swing.JComboBox<Docente> cbxDocente;
    private javax.swing.JComboBox<Estudiante> cbxEstudiante;
    private javax.swing.JComboBox<Horario> cbxHorario;
    private javax.swing.JComboBox<NumJornada> cbxJornada;
    private javax.swing.JComboBox<Materia> cbxMateria;
    private javax.swing.JComboBox<Programa> cbxPrograma;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblCurso;
    private javax.swing.JTable tblCursoEstudiante;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtLlenarPeriodo;
    // End of variables declaration//GEN-END:variables
}
