package vista;

import Util.IList;
import Util.Lista;
import controladores.ControladorGestionEstudiante;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import modelo.Curso;
import modelo.DetalleNota;
import modelo.Estudiante;
import modelo.Nota;
import modelo.Usuario;

/**
 *
 * @author JOAN
 */
public class VentanaNotasEstudiante extends javax.swing.JFrame {

    Estudiante estudiante;
    ControladorGestionEstudiante controlador;
    IList<Nota> listaNota;

    public VentanaNotasEstudiante(Usuario usuario) {
        initComponents();
        this.controlador = new ControladorGestionEstudiante(usuario);
        this.estudiante = (Estudiante) usuario;
        LlenarCurso();
    }

    private void LlenarCurso() {
        cbxCurso.removeAllItems();
        IList<Curso> listaCurso = controlador.getListaCurso();
        if (listaCurso != null) {
            for (int i = 0; i < listaCurso.size(); i++) {
                cbxCurso.addItem(listaCurso.get(i));
            }
        }
    }

    private void actualizarTabla(Curso curso) {
        listaNota = new Lista<>();
        for (int i = 0; i < controlador.getListaCurso().size(); i++) {
            if (controlador.getListaCurso().get(i).getCodigoCurso().equals(curso.getCodigoCurso())) {
                for (int j = 0; j < controlador.getListaCurso().get(i).getListaNotas().size(); j++) {
                    listaNota.add(controlador.getListaCurso().get(i).getListaNotas().get(j));
                }
            }
        }
        DefaultTableModel modelo = new DefaultTableModel(new String[]{"DESCRIPCION", "NOTA"}, 0);
        tblCurso.setModel(modelo);
        TableModel modeloDatos = tblCurso.getModel();
        double notaFinal = 0;
        for (int i = 0; i < listaNota.size(); i++) {
            Nota aux = listaNota.get(i);
            DetalleNota detalle = null;
            for (int j = 0; j < aux.getListaDetalle().size(); j++) {
                if (estudiante.getCodigo().equals(aux.getListaDetalle().get(j).getEstudiante().getCodigo())) {
                    detalle = aux.getListaDetalle().get(j);
                    break;
                }
            }
            if (detalle != null) {
                notaFinal += detalle.getValor();
                modelo.addRow(new Object[]{aux.getDescripcion(), detalle.getValor()});
            }
        }
        if (listaNota.size() > 0) {
            notaFinal = notaFinal / listaNota.size();
        }
        String notaFinalFormatted = String.format("%.2f", notaFinal);
        modelo.addRow(new Object[]{"Nota final", notaFinalFormatted});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCurso = new javax.swing.JTable();
        btnAtras = new javax.swing.JButton();
        cbxCurso = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NOTAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        tblCurso.setBackground(new java.awt.Color(204, 204, 204));
        tblCurso.setForeground(new java.awt.Color(0, 0, 0));
        tblCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCurso);

        btnAtras.setBackground(new java.awt.Color(204, 204, 204));
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Atras.png"))); // NOI18N
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        cbxCurso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxCursoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAtras))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        VentanaEstudiante ventana = new VentanaEstudiante(estudiante);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void cbxCursoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxCursoItemStateChanged
        Curso curso = (Curso) cbxCurso.getSelectedItem();
        actualizarTabla(curso);
    }//GEN-LAST:event_cbxCursoItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JComboBox<Curso> cbxCurso;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCurso;
    // End of variables declaration//GEN-END:variables
}
